config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "offers#index"
  get "/myoffers", to: "pages#myoffers", as: "myoffers"
  get "/mybookings", to: "pages#mybookings", as: "mybookings"

  resources :offers do
    resources :bookings, only: [:create, :destroy]
    resources :reviews, only: :create
  end

  resources :bookings, only: [] do
    member do
      patch 'accept'
      patch 'reject'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  #associations
  belongs_to :user
  belongs_to :offer

  #validations
  validates :user_id, presence: true
  validates :offer_id, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :status, inclusion: { in: %w[pending accepted rejected] }

  # Scopes to filter bookings by status
  scope :pending, -> { where(status: 'pending') }
  scope :accepted, -> { where(status: 'accepted') }
  scope :rejected, -> { where(status: 'rejected') }
end

app/models/offer.rb
class Offer < ApplicationRecord
  include PgSearch::Model
  # cloudinary
  has_one_attached :image

  # associations
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy

  # validations
  validates :name, presence: true, uniqueness: true
  validates :address, presence: true
  validates :description, presence: true
  validates :user_id, presence: true

  # geocoding
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  # pg_search
  pg_search_scope :search_by_name_and_description,
    against: [ :name, :description ],
    associated_against: {
      user: [:username]
    },
    using: {
      tsearch: { prefix: true }
  }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :offer

  #validations
  validates :rating, presence: true
  validates :content, presence: true, length: { minimum: 10, message: "must be at least 20 characters long" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  # cloudinary
  has_one_attached :image

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :offers, through: :bookings
  has_many :offers, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy

  #validations
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username, :url_image, :image])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :username, :url_image, :image])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:destroy, :accept, :reject]

  def create
    @user = current_user
    @offer = Offer.find(params[:offer_id])
    @booking = Booking.new(booking_params)
    @booking.user = @user
    @booking.offer = @offer
    @booking.status = "pending"
    if @booking.save
      redirect_to mybookings_path, notice: "Votre demande de réservation a été envoyée."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def new

  end
  def destroy
    @booking.destroy
    redirect_to mybookings_path, status: :see_other
  end

  def accept
    @booking.update(status: 'accepted')
    redirect_to myoffers_path, notice: 'Réservation acceptée.'
  end

  def reject
    @booking.update(status: 'rejected')
    redirect_to myoffers_path, notice: 'Réservation refusée.'
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :set_offer, only: [:show, :edit, :update, :destroy]

  def index
    @offers = Offer.all
    if params[:search].present? && params[:search][:query].present?
      @offers = Offer.search_by_name_and_description(params[:search][:query])
    else
      @offers = Offer.all
    end
    @markers = @offers.geocoded.map do |offer|
      {
        lat: offer.latitude,
        lng: offer.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { offer: offer })
      }
    end
  end

  def show
    @booking = Booking.new
    @review = Review.new
    @offer = Offer.find(params[:id])
    @markers = [{
      lat: @offer.latitude,
      lng: @offer.longitude,
      info_window_html: render_to_string(partial: "info_window", locals: { offer: @offer })
    }]
    @reviews = @offer.reviews
  end

  def new
    @offer = Offer.new
  end

  def edit
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.user = current_user
    if @offer.save!
      redirect_to offer_path(@offer)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @offer.update(offer_params)
      redirect_to offer_path(@offer)
    else
      render :edit
    end
  end

  def destroy
    @offer.destroy
    redirect_to myoffers_path, status: :see_other
  end

  private

  def set_offer
    @offer = Offer.find(params[:id])
  end

  def offer_params
    params.require(:offer).permit(:name, :address, :price, :description, :image)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def mybookings
  end

  def myoffers
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @user = current_user
    @offer = Offer.find(params[:offer_id])
    @review = Review.new(review_params)
    @review.user = @user
    @review.offer = @offer
    if @review.save
      # Si l'offre n'a pas encore de note (première review)
      if @offer.rating.nil?
        new_rating = @review.rating
      else
        # Calculer la nouvelle note moyenne
        new_rating = ((@offer.rating * @offer.reviews.count) + @review.rating) / (@offer.reviews.count + 1)
      end

      # Mettre à jour la colonne rating de l'offre
      @offer.update(rating: new_rating)

      # Rediriger avec un message de succès
      redirect_to offer_path(@offer), notice: "Votre review a été créée avec succès."
    else
      # Renvoyer le formulaire avec les erreurs
      render :new, status: :unprocessable_entity
    end
  end

  def new

  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<div class="footer bottom: 0" data-controller="sound">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github" data-action="click->sound#playsound"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> by UnrealBnB©
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon bg-light sticky-top">
  <div class="container-fluid">

    <%= link_to root_path, class: "navbar-brand d-flex" do %>
      <%= image_tag 'Logo.png' %>
      <p id="logo", class="modal-dialog modal-dialog-centered fw-medium fs-2">UnrealBnB©</p>
    <% end %>

    <% if user_signed_in? %>
      <div class="navbar-text-center-custom">
        <h4>Bienvenue <%= current_user.username %> <%= image_tag 'Castle.png' %> </h4>
      </div>
    <%end%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Mes réservations", mybookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Mes offres", myoffers_path, class: "nav-link me-2" %>
          </li>
          <li class="nav-item dropdown">
            <%= render 'layouts/set_vava', vava: current_user %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_notice.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger alert-dismissible" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/_searchbar.html.erb
<%= simple_form_for :search, url: root_path, method: :get do |f| %>
  <div class="search-form-control form-group">
    <%= f.input :query, label: false, placeholder: "Rechercher", input_html: { value: params[:search] && params[:search][:query] } %>
    <button type="submit" class="btn btn-flat">
      <i class="fa-brands fa-searchengin fs-3 icon-blue"></i>
    </button>
  </div>
<% end %>

app/views/layouts/_set_vava.html.erb
<%= image_tag(
      (if vava.image.attached?
         cl_image_path(vava.image.key, crop: :crop, gravity: :face, width: 300, height: 300)
       elsif vava.url_image.nil?
         "https://img.freepik.com/free-photo/androgynous-avatar-non-binary-queer-person_23-2151100270.jpg?size=626&ext=jpg&ga=GA1.1.56337491.1723629018&semt=ais_hybrid"
       else
         vava.url_image
       end),
      class: "avatar dropdown-toggle",
      id: "navbarDropdown",
      data: { bs_toggle: "dropdown" },
      'aria-haspopup': true,
      'aria-expanded': false
    ) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UnrealBnB</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=MedievalSharp&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/searchbar' %>
    <div style="min-height: 90vh;"><%= yield %></div>
    <%= render 'layouts/notice' %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/offers/_form.html.erb
<%= simple_form_for offer do |f| %>
  <%= f.input :name %>
  <%= f.input :address,
    input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
    wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
  %>
  <%= f.input :price %>
  <%= f.input :description %>
  <%= f.input :image, as: :file %>
  <%= f.submit "Créer l'offre", class: 'btn btn-primary' %>
<% end %>

app/views/offers/_image_set.html.erb
<%= if item.image.attached?
      cl_image_path(item.image.key)
    elsif item.url_image.nil?
      "https://images.pexels.com/photos/691668/pexels-photo-691668.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
    else
      item.url_image.strip
end %>

app/views/offers/_info_window.html.erb
<img src="<%= offer.url_image %>" class="card-img-top" alt="<%= offer.name %>">
<div class="card-body" >
  <h2 class="card-title"><%= offer.name %></h2>
  <%= link_to 'Voir cette offre', offer_path(offer), class: 'btn btn-secondary' %>
  <p class="card-text"><%= offer.description.truncate(100) %></p>
</div>

app/views/offers/edit.html.erb
<div class = "container mt-4">
  <h1>Edit <%= @offer.name %></h1>

  <%= render "form", offer: @offer %>
  <hr>
  <%= link_to "Back to Offers ", root_path  %>
</div>

app/views/offers/index.html.erb
<div class= "container mt-4" data-controller="sound">
  <h1 class="mb-4">Louez l’impossible, vivez l’extraordinaire.</h1>
  <div class="d-flex flex-wrap" data-controller="scroll-animation">
    <% if @offers.present? %>
      <% @offers.each do |offer| %>
        <div class="card m-3" style="width: 18rem; border-radius: 15px" data-scroll-animation-target="card">
          <%= link_to offer_path(offer) do %>
            <img src="<%= if offer.image.attached?
                          cl_image_path(offer.image.key)
                        elsif offer.url_image.nil?
                          'https://images.pexels.com/photos/691668/pexels-photo-691668.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'
                        else
                          offer.url_image.strip
                        end %>" class="card-img-top" alt="<%= offer.name %>" style="height: 200px;">
            <% end %>
          <div class="card-body">
            <h5 class="card-title"><strong><%= offer.name %></strong></h5>
            <p class="card-text mb-2"><%= offer.description.truncate(100) %></p>
            <%= link_to 'Voir cette offre', offer_path(offer), class: 'btn btn-outline-info index-button-blue-green w-100 mt-auto', data: { action: 'click->sound#playsoundLetsgo' } %>
            <div class="d-flex justify-content-between mt-3">
              <p class="card-text"><i class="fa-solid fa-house-user icon-blue-green"></i> <%= offer.user.username%></p>
              <p class="card-text text-end"><i class="fa-solid fa-coins icon-yellow"></i> <%= offer.price.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1,').reverse%></p>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <p>No offers available.</p>
    <% end %>
  </div>
  <hr>
  <h2> Explore with our map.</h2>
  <br>
  <div style="width: 100%; height: 600px;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

  <%# AUDIO NE PAS REACTIVER TOUT DE SUITE %>
  <%# <audio type="audio/mp3" src="home-audio.mp3" autoplay loop> %>
</div>

app/views/offers/new.html.erb
<div class = "container mt-4">
  <h1>Rentrez votre nouvelle offre</h1>

  <%= render "form", offer: @offer %>
</div>

app/views/offers/show.html.erb
<div class="map" style="background-image: url('<%= if @offer.image.attached?
      cl_image_path(@offer.image.key)
    elsif @offer.url_image.nil?
      'https://images.pexels.com/photos/691668/pexels-photo-691668.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'
    else
      @offer.url_image.strip
    end %>');">
</div>
<div class="container margin-top-negative">
  <div class="row">
    <div class="col-8">
      <div class="offer-show-card">
        <div class="position-relative">
          <h1><%= @offer.name %></h1>
          <div class="position-absolute top-0 end-0">
            <div class="d-flex align-items-center pt-2" style="font-size: 24px;">
              <i class="fw-bold mx-2 fa-solid fa-star icon-yellow"></i>
              <p class="mb-0" > <%= @offer.rating == nil ? "NR" : @offer.rating.round(1) %> </p>
            </div>
          </div>
        </div>
        <hr>
        <div class="d-flex mb-3">
          <%= render 'layouts/set_vava', vava: @offer.user %>
          <p class="fw-bold mx-3 pt-2"><%= @offer.user.username  %> </p>
        </div>
        <p><%= @offer.description %></p>
        <div class="d-flex justify-content-between pt-3">
          <p class="offer-show-address mb-0 text-blue"><i class="fa-solid fa-location-dot fa-bounce icon-blue px-2 mb-3"></i><%= @offer.address %></p>
          <p class="price mb-0 no-bold"><i class="fa-solid fa-coins icon-yellow fa-beat px-2 mb-3"></i><%= @offer.price.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1,').reverse %></p>
        </div>
      </div>
    </div>
    <!-- Ajouter des bookings -->
    <div class="col-4">
      <div class="offer-show-card">
        <h5>Reservation</h5>
          <%= simple_form_for [@offer, @booking] do |f| %>
            <%= f.input :start_date, input_html: {data: {controller:'datepicker', datepicker_target: "start"}, placeholder: "select dates"}, as: :string %>
            <%= f.input :end_date, input_html: {data: {controller:'datepicker', datepicker_target: "end"}, placeholder: "select dates"}, as: :string %>
            <%= f.submit "Réserver", class: "btn btn-primary rounded" %>
          <% end %>
      </div>
    </div>
  </div>
<%# commentaires %>
  <div class="overflow-auto mt-5" style="height: 200px;">
    <% @reviews.each do | review | %>
      <div class="card mb-4 shadow-sm">
        <div class="card-body">
          <div class="d-flex align-items-center mb-2">
            <!-- Avatar et Nom d'utilisateur -->
            <div class="d-flex align-items-center me-3">
              <div class="me-2">
                <%= render 'layouts/set_vava', vava: review.user %> <!-- Avatar du user -->
              </div>
              <h5 class="mb-0">
                <i class="fas fa-user-circle"></i> <!-- Icone utilisateur FontAwesome -->
                <%= review.user.username %> <!-- Nom d'utilisateur -->
              </h5>
            </div>

            <!-- Évaluation (rating) -->
            <div>
              <span class="badge <%= review.rating > 3 ? 'bg-success' : (review.rating >= 2 ? 'bg-warning' : 'bg-danger') %>">
                <%= review.rating %> ★
              </span>
            </div>
          </div>

          <!-- Contenu de la review -->
          <p class="card-text">
            <%= review.content %>
          </p>
        </div>
      </div>
    <% end %>
  </div>

  <!-- Formulaire d'ajout de commentaire -->
  <%= simple_form_for [@offer, @review] do |f| %>
    <div class="mb-3">
      <%= f.input :content, label: false, placeholder: "Votre commentaire"%>
    </div>
    <div class="mb-3">
      <%= f.input :rating, label: false, placeholder: "Votre note"%>
    </div>
    <div>
      <%= f.submit "Créer commentaire", class: 'btn btn-primary' %>
    </div>
  <% end %>


  <div class="mt-5 " style="width: 100%; height: 600px;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/pages/mybookings.html.erb
<div class="container mt-4" data-controller="sound">
  <h1 class="mb-4">Mes réservations imaginaires</h1>
  <div class="d-flex flex-wrap">
    <% current_user.bookings.each do |booking| %>
      <div class="card m-3" style="width: 18rem; border-radius: 15px">
           <%= link_to offer_path(booking.offer) do %>
            <img src="<%= if booking.offer.image.attached?
                          cl_image_path(booking.offer.image.key)
                        elsif booking.offer.url_image.nil?
                          'https://images.pexels.com/photos/691668/pexels-photo-691668.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'
                        else
                          booking.offer.url_image.strip
                        end %>" class="card-img-top" alt="<%= booking.offer.name %>"  style="height: 200px; object-fit: cover; width: 100%;" >
            <% end %>
        <div class="card-body">
          <h5 class="card-title"><strong><%= booking.offer.name %></strong></h5>
          <p class="card-text mb-2">Détails de la réservation</p>
          <p class="card-text mb-2"><u>Début :</u> <%= booking.start_date %></p>
          <p class="card-text mb-2"><u>Fin :</u> <%= booking.end_date %></p>
          <p class="card-text mb-2">
            <% if booking.status == 'pending' %>
              <i class="fa-solid fa-hourglass-half text-warning"></i>
              <span class="text-orange"> En attente de validation</span>
            <% elsif booking.status == 'accepted' %>
              <i class="fa-solid fa-circle-check text-success"></i>
              <span class="text-green"> Réservation acceptée</span>
            <% elsif booking.status == 'rejected' %>
              <i class="fa-solid fa-xmark text-danger"></i>
              <span class="text-red"> Réservation refusée</span>
            <% end %>
          </p>
          <div class="text-end mt-auto">
            <%= button_to 'Annuler', offer_booking_path(booking.offer, booking), method: :delete, data: { turbo_confirm: 'Vous êtes sûr?' }, class: 'btn btn-outline-danger rounded-pill' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <p class="w-100"><%= link_to "Chercher une nouvelle location", new_offer_path, class: "btn btn-primary btn-lg w-100 link-underline link-underline-opacity-0 mb-3 mt-2" , data: { action: 'click->sound#playsoundGotit' }%></p>
</div>

app/views/pages/myoffers.html.erb
<div class="container mt-4" data-controller="sound">
  <h1 class="mb-4">Détails de vos offres</h1>
  <div class="d-flex flex-wrap">
    <% current_user.offers.each do |offer| %>
      <div class="card m-3" style="width: 18rem; border-radius: 15px">
          <%= link_to offer_path(offer) do %>
          <img src="<%= if offer.image.attached?
                        cl_image_path(offer.image.key)
                      elsif offer.url_image.nil?
                        'https://images.pexels.com/photos/691668/pexels-photo-691668.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'
                      else
                        offer.url_image.strip
                      end %>" class="card-img-top" alt="<%= offer.name %>" style="height: 200px;">
          <% end %>
        <div class="card-body">
          <h5 class="card-title"><strong><%= offer.name %></strong></h5>
          <p class="card-text mb-2"><%= offer.description %></p>
          <p class="card-text text-end"><i class="fa-solid fa-coins icon-yellow"></i> <%= offer.price.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1,').reverse%></p>
          <hr>
            <% if offer.bookings.pending.any? %>
              <p class="card-text mb-1">Demandes de réservation : <%= offer.bookings.pending.count %></p>
              <ul class="list-group list-group-flush">
                <% offer.bookings.pending.each do |booking| %>
                  <li class="list-group-item">
                    <div class="d-flex justify-content-start modal-dialog modal-dialog-centered gap-2">
                      <%= render 'layouts/set_vava', vava: booking.user %>
                      <p class="card-text mt-0 p-0"><%= booking.user.username %></p>
                    </div>
                    <p class="card-text">Du <%= booking.start_date %> au <%= booking.end_date %></p>
                    <div class="d-flex justify-content-center p-2 gap-3" >
                      <%= button_to 'Accepter', accept_booking_path(booking), method: :patch, class: 'btn btn-success btn-sm rounded opacity-75', data: { action: 'click->sound#playsoundValidation' } %>
                      <%= button_to 'Refuser', reject_booking_path(booking), method: :patch, class: 'btn btn-danger btn-sm rounded opacity-75', data: { action: 'click->sound#playsoundYahaha' } %>
                    </div></li>
                <% end %>
              </ul>
            <% else %>
              <p class="card-text mb-2 text-muted"><i>Pas de demande en attente</i></p>
            <% end %>
          <hr>
          <div class="d-flex justify-content-between mt-3">
            <%= link_to 'Modifier', edit_offer_path(offer), class: 'btn btn-outline-secondary rounded-pill' %>
            <%= button_to 'Supprimer', offer_path(offer), method: :delete, data: { turbo_confirm: 'Are you sure?' }, class: 'btn btn-outline-danger rounded-pill', data: { action: 'click->sound#playsoundYahaha' } %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <p class="w-100"><%= link_to "Ajouter une nouvelle location", new_offer_path, class: "btn btn-primary btn-lg w-100 link-underline link-underline-opacity-0 mb-3 mt-2", data: { action: 'click->sound#playsoundGotit' } %></p>
</div>